srgb = false         # platform-specific: false (Linux/macOS) or true (Windows)
tabs = false
title-hidden = false
vsync = true
wsl = false

[font]
normal = [] # Will use the bundled Fira Code Nerd Font by default
size = 14.0

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4] # Thin and thick values respectively, for all sizes
