return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "beautysh",
        "black",
        "codelldb",
        "eslint-lsp",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "prettier",
        "pyright",
        "shellcheck",
        "shfmt",
        "stylua",
        "taplo",
        "typescript-language-server",
        "yaml-language-server",
        "arduino-language-server",
        "cpplint",
        "docker-language-server",
        "dockerfile-language-server",
        "docker-compose-language-service",
        "clang-format",
      },
    },
  },
}
