config_worktree_folder="$HOME"
git_dir="${config_worktree_folder}/.cfg/"
alias configotofolder="cd ${config_worktree_folder}"
alias config="git --git-dir=${git_dir} --work-tree=${config_worktree_folder}"
alias configst="config status"
alias configadd="config add ${config_worktree_folder}/.config/nvim && config status"
alias conf="configadd"
alias configlazygit="lazygit --git-dir=${config_worktree_folder}/.cfg/ --work-tree=${config_worktree_folder}"
